---
- name: Configuring the EC2 Instance
  hosts: localhost
  connection: local
  vars:
       count: {{ count }}
       volumes:
               - device_name: /dev/sda1
                 volume_size: {{ volume-size }}    
 
- name: Launching an EC2 Instance
  local_action: ec2
  instance_type={{ instance_type}}
  image={{ ami }}
  region={{ region }}
  keypair={{ pem }}
  count={{count}}
  instance_profile_name={{ instance_profile_name }}
  group={{ security_group }}
  wait=true
  volumes={{volumes}}
  register: ec2
 
- name: Associating after allocating elastic IP
  eip:
      in_vpc: yes
      reuse_existing_ip_allowed: yes
      state: present
      region: "{{ region }}"
      device_id: "{{ ec2.instance_id[0] }}"
      register: elastic_ip
 
- name: Waiting for the instance to come
  local_action: wait_for
              host={{ item.private_ip }}
              state=started
              port=22
  with_items: ec2.instance
 
- name: Adding tags to the EC2 Instance"
  local_action: ec2_tag
              region={{ region }}
              resource={{ item.id }}
              state=present
  with_items: ec2.instances
  args:
   tags:
       Name: "{{ name }}"
       Env: "{{ Env }}"
       Type: microservice
  register: tag
